import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from models import DigestItem

# Accent color for relevance badges and highlights
_ACCENT = "#4F46E5"
_BADGE_BG = "#EEF2FF"


def _tag_pill(tag: str) -> str:
    return (
        f'<span style="display:inline-block;background:#F3F4F6;color:#374151;'
        f'font-size:11px;font-weight:600;padding:2px 8px;border-radius:999px;'
        f'margin:2px 3px 2px 0;letter-spacing:0.03em;">{tag}</span>'
    )


def _render_html(items: list[DigestItem], run_date: date) -> str:
    date_str = run_date.strftime("%B %-d, %Y")
    item_cards = []

    for item in items:
        v = item.video
        highlighted = set(item.relevant_insights)

        # Score badge
        badge = ""
        if item.relevance_score > 0:
            badge = (
                f'<span style="display:inline-block;background:{_BADGE_BG};color:{_ACCENT};'
                f'font-size:12px;font-weight:700;padding:2px 10px;border-radius:999px;'
                f'margin-left:10px;vertical-align:middle;">★ {item.relevance_score}/10</span>'
            )

        # Insights
        insight_items = []
        for i, insight in enumerate(item.insights):
            if i in highlighted:
                insight_items.append(
                    f'<li style="margin:5px 0;"><strong style="color:#111827;">{insight}</strong></li>'
                )
            else:
                insight_items.append(f'<li style="margin:5px 0;color:#374151;">{insight}</li>')
        insights_html = (
            f'<ul style="margin:10px 0 0 0;padding-left:20px;line-height:1.6;">'
            + "".join(insight_items)
            + "</ul>"
            if insight_items else ""
        )

        # Tags
        tags_html = (
            '<div style="margin-top:12px;">' + "".join(_tag_pill(t) for t in item.tags) + "</div>"
            if item.tags else ""
        )

        card = f"""
        <div style="background:#FFFFFF;border:1px solid #E5E7EB;border-radius:10px;
                    padding:20px 24px;margin-bottom:16px;">
          <h2 style="margin:0 0 4px 0;font-size:17px;font-weight:700;line-height:1.4;">
            <a href="{v.url}" style="color:#111827;text-decoration:none;">{v.title}</a>
            {badge}
          </h2>
          <p style="margin:0 0 12px 0;font-size:12px;color:#6B7280;">
            {v.channel} &nbsp;·&nbsp; {v.published_at.strftime("%B %-d, %Y")}
          </p>
          <p style="margin:0;font-size:14px;color:#374151;line-height:1.65;">{item.summary}</p>
          {insights_html}
          {tags_html}
        </div>
        """
        item_cards.append(card)

    cards_html = "\n".join(item_cards)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F9FAFB;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:24px 16px 40px;">

    <!-- Header -->
    <div style="background:{_ACCENT};border-radius:10px;padding:24px 28px;margin-bottom:24px;">
      <h1 style="margin:0;color:#FFFFFF;font-size:22px;font-weight:700;letter-spacing:-0.02em;">
        Personal Digest
      </h1>
      <p style="margin:4px 0 0 0;color:#C7D2FE;font-size:14px;">{date_str} &nbsp;·&nbsp; {len(items)} video{"s" if len(items) != 1 else ""}</p>
    </div>

    <!-- Items -->
    {cards_html}

    <!-- Footer -->
    <p style="text-align:center;font-size:11px;color:#9CA3AF;margin-top:8px;">
      Generated by personal-digest
    </p>
  </div>
</body>
</html>"""


def send_email(items: list[DigestItem], cfg: dict, to_override: list[str] | None = None) -> None:
    """Send the digest as an HTML email. cfg is the 'email' block from config.yaml."""
    if not cfg.get("enabled", False) and not to_override:
        return
    to_addresses: list[str] = to_override if to_override else cfg.get("to", [])
    if not to_addresses:
        return

    smtp_host: str = cfg.get("smtp_host", "smtp.gmail.com")
    smtp_port: int = int(cfg.get("smtp_port", 587))
    username: str = cfg.get("username", "")
    # Password: config.yaml value, or DIGEST_EMAIL_PASSWORD env var
    password: str = os.environ.get("DIGEST_EMAIL_PASSWORD") or cfg.get("password", "")
    from_addr: str = cfg.get("from", username)

    if not username or not password:
        print("[email] Skipping — smtp username or password not configured")
        return

    today = date.today()
    subject = f"Personal Digest {today.strftime('[%Y-%m-%d]')}"
    html_body = _render_html(items, today)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addresses)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(username, password)
            server.sendmail(from_addr, to_addresses, msg.as_string())
        print(f"[email] Sent to {', '.join(to_addresses)}")
    except Exception as e:
        print(f"[email] Failed to send: {e}")
